[gcp_service_account]
type = "service_account"
project_id = "loyal-saga-440022-e1"
private_key_id = "f3a02e4256db1450870dbded43a36b4de3ef52f6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCUOXnH//LQpNAu
N8QfvcgYsHlQ70jwoK9Pj3cL6tfZLJ1TihosJyOcA6BjLd8QsAYb5C8Y05tyfz/p
W6Tm0xGGgOKYpn4eB4ody9n/ejj0/518zyG1ozEk2/YGI+mX6eCbS2GzIif1YUYm
nb4EEQnDdrrn1IS/bF512ZsFsn/tf+xJN++wCgSauZNpA07O27TuKTZiECILnfpy
4O8B8IsLu+TXVTgRt07yIseZ+Q2EBRJOPipspumaMa5ocM5OSQuh59GwhVxlaseQ
7jHuCQxHUPWggeBJwdzwcXfiltVnoRwN6pF9FUkksAEFU8OqQeXyf8hoX+nyD/O7
v+d5IEZLAgMBAAECggEACUKwA5lPk86APSr5w1vpiPVZlv9kKLh5S3i0oNd6xdQ+
Pg5mRTTqyiAF4Lxob9P3hb2TXbM2xogBt7QkkNFGCoe54Hyia4DgFa17QLVjopbn
wXj1a7I2600cyVRsDzQq9rjWcUkkgvWhWt9HFFz2JbKgycQiyQzdt/Iw98GnsXBQ
uFvbVqar7MUwcKCsbbA0+IqAxNwC1JXTeKJO6WYQfmxnmBC0MuaL3idbxWgWaU2p
CFlfLVGbe7347J99yZQ7zTmVBxX6gsg1OeVIWhQPcO4yRoG3jhVVBkDIvrtdxT9h
s2GKyXY/8VhBVt3X7UNU9JmtSlBp+nkBnrfW+jwP4QKBgQDKngP6uC28V/EpA8rM
4UD/bYMQqTpq9eTKbgsbvI+SLIdm3r4gBHS1kEakgANejRL3Los1GLUzWxPX20R8
+Hy2cI9BY+fcrRgxhqOXxD4Cfg86sKqEzSeFFjTdc7bShaeBemPjmYrPGf7kC4nR
QUjK/pM0qPb0ZVTs4Ht7gHUbqwKBgQC7RtFQkFJqHuM5i5JJcoUA68CbPg25TGPP
HGOP076zYOJF+9KhaHc6Bbfg54M3JXVSDLK04tqPPd5t8dcax46pUeV5d8lySuTT
nmhY/ehUOGHyqdDp5SXzN3BnUdOBrAoc84vLrkTlCzX+fPtSWENmbBW5WxRI7lxs
gTSfXEvf4QKBgAc/L5VAESKzYoS9Bfvd8p0wJYfrBZPdx5kV5n/PdrMbtJwRS2uJ
vULhLiWkDnrLQOpmV8RGZfS4RTVrOj/eA1fjHryP/jL+XecnkaJT+oPMTm8i8nZd
gBRafvmMsfVFooAXCIuTakuN+nfdkchSNXBNOqafhHWpSihOvxvjtEyRAoGAR3ZO
iR+JU1VV/69ysvQwLJnJdXPIaNzteSqsE0YJjwl5Tps5VL44QLvN3tR5DaINkrGl
v8CRBffl2K5gFqfvmEzX8/HxvNs3VkksKEk7Tmf1eFO0lIwMXzLYgZSH0QOFGGcX
ATIOuBf/Eo0+mb10erDj2UcYBnxuaDkli2n8ygECgYBcU2N3/yaNS1zl1PGxWP5T
rJLY6c3Ha0c5uDSoq85wSQmswTDcTGXjyAijyJR42txE7ilLFkt97EUSaGv4A5If
M2GhAChRTUSnUTWyyNCBJbuGNKmaIa+T0p6J/ec6EUktlZDH61UYNZAMy8j52M6w
z1z9mg9rR1Ds1NgGHBEYYg==
-----END PRIVATE KEY-----"""
client_email = "fisrt-phyton@loyal-saga-440022-e1.iam.gserviceaccount.com"
client_id = "114683278940949585747"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fisrt-phyton%40loyal-saga-440022-e1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
